# Generated by Django 6.0.5 on 2026-06-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0002_add_anti_overbooking_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="bloque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="turnos.bloquedisponibilidad",
            ),
        ),
    ]
